"""
Top-DMA ranking for audience segments.

Python port of ari-api's campaign-analysis/lib/dma-targeting.ts — keep the two
in sync. Scores every Nielsen DMA against a segment's targeting params using
the ACS-derived demographics dataset (data/dma_demographics.json, generated by
ari-api's `npm run data:dma` from county-level ACS 5-year data + a public
county->DMA crosswalk) and returns the markets where the audience is most
concentrated.

Pure and synchronous: parsers turn the LLM's semi-structured targeting strings
into census buckets; unparseable attributes are simply omitted from scoring,
so the worst case (nothing parseable) degrades to a population ranking with
every index at 100 — never a throw, never empty.
"""
import json
import math
import os
import re
from functools import lru_cache

# ACS age tables top-code at 85+; treat parsed ranges within [18, 99].
AGE_MIN = 18
AGE_MAX = 99

# Age brackets, in order, matching the dataset's ageGender count arrays.
AGE_BRACKETS = [(18, 24), (25, 34), (35, 44), (45, 54), (55, 64), (65, 99)]

# Household-income bucket bounds in dollars ([min, max), None = open-ended),
# matching the dataset's income count arrays.
INCOME_BUCKETS = [
    (0, 25000),
    (25000, 50000),
    (50000, 75000),
    (75000, 100000),
    (100000, 150000),
    (150000, 200000),
    (200000, None),
]

EDUCATION_GROUPS = {
    "graduate_plus": ["graduate"],
    "bachelor_plus": ["bachelor", "graduate"],
    "some_college": ["someCollegeNoDegree", "associate"],
    "hs_non_degree": ["hsGrad", "someCollegeNoDegree"],
}

ETHNICITY_FIELDS = {
    "hispanicLatino": "hispanicLatino",
    "black": "black",
    "asian": "asian",
    "nativeAmerican": "nativeAmerican",
    "pacificIslander": "pacificIslander",
}

# Eligibility floors keep statistical-noise micro-markets out of the ranking
# while still admitting small high-concentration DMAs (e.g. Laredo). Relaxed
# progressively so the function always returns up to `limit` entries.
POPULATION_FLOOR = 150_000
EST_AUDIENCE_FLOOR = 30_000
RELAXED_POPULATION_FLOOR = 50_000

_DATASET_PATH = os.path.join(
    os.path.dirname(__file__), "..", "data", "dma_demographics.json"
)


@lru_cache(maxsize=1)
def load_dma_dataset():
    """Load (and cache) the DMA demographics dataset."""
    with open(_DATASET_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def _round_half_up(x):
    """JS Math.round parity (Python's round() is banker's rounding)."""
    return math.floor(x + 0.5)


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

def parse_age_targeting(raw):
    """Parse '25-34' / '35+' / '18 to 24' into (min, max), clamped to adults."""
    if not raw:
        return None
    parsed = None
    m = re.search(r"(\d{1,2})\s*[-–]\s*(\d{1,2})", raw)
    if m:
        parsed = (int(m.group(1)), int(m.group(2)))
    else:
        m = re.search(r"(\d{1,2})\s*\+", raw)
        if m:
            parsed = (int(m.group(1)), 99)
        else:
            m = re.search(r"(\d{1,2})\s*(?:to|through)\s*(\d{1,2})", raw, re.I)
            if m:
                parsed = (int(m.group(1)), int(m.group(2)))
    if not parsed:
        return None
    lo = max(AGE_MIN, min(parsed[0], AGE_MAX))
    hi = max(AGE_MIN, min(parsed[1], AGE_MAX))
    return (lo, hi) if lo <= hi else None


def parse_gender_targeting(raw):
    if not raw:
        return None
    lower = raw.lower()
    # "female" must win over the "male" substring it contains.
    if re.search(r"\bfemales?\b|\bwomen\b", lower):
        return "female"
    if re.search(r"\bmales?\b|\bmen\b", lower):
        return "male"
    return None


def parse_income_targeting(raw):
    """Parse income strings into {'min': int, 'max': int|None} or None."""
    if not raw:
        return None
    lower = raw.lower()

    numbers = []
    for m in re.finditer(r"(\d{1,3}(?:,\d{3})+|\d+(?:\.\d+)?)\s*(k)?", lower):
        value = float(m.group(1).replace(",", ""))
        if m.group(2):
            value *= 1000
        elif value < 1000:  # "$50-$100" means thousands
            value *= 1000
        numbers.append(value)

    if len(numbers) >= 2:
        return {"min": min(numbers[0], numbers[1]), "max": max(numbers[0], numbers[1])}
    if len(numbers) == 1:
        n = numbers[0]
        if re.search(r"below|under|less than|up to", lower):
            return {"min": 0, "max": n}
        if re.search(r"above|over|more than|plus|\+", lower):
            return {"min": n, "max": None}
        return None  # a bare number is ambiguous
    # No numbers: coarse keyword fallback.
    if re.search(r"affluent|high[- ]income|luxury|premium|wealthy|upscale", lower):
        return {"min": 100000, "max": None}
    if re.search(r"middle[- ]income|mid[- ]income|moderate income", lower):
        return {"min": 50000, "max": 100000}
    if re.search(r"low[- ]income|budget|value[- ]conscious", lower):
        return {"min": 0, "max": 50000}
    return None


def parse_education_targeting(raw):
    if not raw:
        return None
    lower = raw.lower()
    if re.search(r"graduate|master|phd|doctor|postgrad|advanced degree", lower):
        return "graduate_plus"
    if re.search(r"some college|associate", lower):
        return "some_college"
    if re.search(r"bachelor|college|university|degree", lower):
        return "bachelor_plus"
    if re.search(r"high school", lower):
        return "hs_non_degree"
    return None


def detect_ethnicity_from_name(name):
    """
    Ethnicity emphasis comes from the segment NAME only: the generation prompt
    requires ethnicity in the name when the brief targets an ethnic audience
    and forbids inferring it otherwise, so interests/description must NOT be
    scanned. No "white" detection — "white-collar" would false-positive and a
    majority share indexes ~flat.
    """
    lower = (name or "").lower()
    if re.search(r"\bhispanic\b|\blatino\b|\blatina\b|\blatinx\b", lower):
        return "hispanicLatino"
    if re.search(r"\bblack\b|\bafrican[- ]american\b", lower):
        return "black"
    if re.search(r"\basian\b|\baapi\b", lower):
        return "asian"
    if re.search(r"\bnative american\b|\bamerican indian\b", lower):
        return "nativeAmerican"
    if re.search(r"\bpacific islander\b|\bhawaiian\b", lower):
        return "pacificIslander"
    return None


def parse_segment_profile(segment):
    params = segment.get("targeting_params") or {}
    return {
        "age_range": parse_age_targeting(params.get("age_range")),
        "gender": parse_gender_targeting(params.get("gender_targeting")),
        "income": parse_income_targeting(params.get("income_targeting")),
        "education": parse_education_targeting(params.get("education_targeting")),
        "ethnicity": detect_ethnicity_from_name(segment.get("name", "")),
    }


# ---------------------------------------------------------------------------
# Shares
# ---------------------------------------------------------------------------

def _age_bracket_fractions(age_range):
    """Fraction of each AGE_BRACKETS entry covered by the range, by year overlap."""
    fractions = []
    for b_min, b_max in AGE_BRACKETS:
        overlap = min(age_range[1], b_max) - max(age_range[0], b_min) + 1
        fractions.append(max(0, overlap) / (b_max - b_min + 1))
    return fractions


def _age_gender_share(dma, age_range, gender):
    """Share of a DMA's population matching the age range (and gender if set)."""
    if dma["population"] == 0:
        return 0.0
    fractions = _age_bracket_fractions(age_range)
    count = 0.0
    for i, fraction in enumerate(fractions):
        if gender != "female":
            count += dma["ageGender"]["male"][i] * fraction
        if gender != "male":
            count += dma["ageGender"]["female"][i] * fraction
    return count / dma["population"]


def _income_share(dma, income):
    """
    Share of a DMA's households inside the income range, by proportional
    bucket overlap. The open-ended 200k+ bucket is treated as 200-300k for
    partial overlaps (fully included once the range itself is open-ended).
    """
    if dma["households"] == 0:
        return 0.0
    range_max = income["max"] if income["max"] is not None else math.inf
    count = 0.0
    for i, (b_min, b_max_raw) in enumerate(INCOME_BUCKETS):
        b_max = b_max_raw if b_max_raw is not None else 300000
        if b_max_raw is None and income["max"] is None:
            effective_range_max = b_max
        else:
            effective_range_max = range_max
        overlap = min(effective_range_max, b_max) - max(income["min"], b_min)
        fraction = max(0.0, overlap) / (b_max - b_min)
        count += dma["income"][i] * min(1.0, fraction)
    return count / dma["households"]


def _education_share(dma, key):
    total = dma["education"]["total25Plus"]
    if total == 0:
        return 0.0
    return sum(dma["education"][k] for k in EDUCATION_GROUPS[key]) / total


def _ethnicity_share(dma, key):
    if dma["population"] == 0:
        return 0.0
    return dma["ethnicity"][ETHNICITY_FIELDS[key]] / dma["population"]


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def _score_dma(dma, national, profile):
    log_indexes = []
    # est_audience multiplies the parsed attribute shares onto the population
    # (independence assumption; income shares are household-based). It is a
    # directional sizing figure, NOT a media-plan reach number. Education is
    # excluded: its 25+-only universe and income correlation would double-count.
    est_audience = float(dma["population"])

    def push(dma_share, national_share):
        if national_share <= 0:
            return
        idx = (dma_share / national_share) * 100
        log_indexes.append(math.log(max(idx, 1)))

    if profile["age_range"]:
        share = _age_gender_share(dma, profile["age_range"], profile["gender"])
        push(share, _age_gender_share(national, profile["age_range"], profile["gender"]))
        est_audience *= share
    if profile["income"]:
        share = _income_share(dma, profile["income"])
        push(share, _income_share(national, profile["income"]))
        est_audience *= share
    if profile["ethnicity"]:
        share = _ethnicity_share(dma, profile["ethnicity"])
        push(share, _ethnicity_share(national, profile["ethnicity"]))
        est_audience *= share
    if profile["education"]:
        push(
            _education_share(dma, profile["education"]),
            _education_share(national, profile["education"]),
        )

    if log_indexes:
        index = math.exp(sum(log_indexes) / len(log_indexes))
    else:
        index = 100.0
    return {"dma": dma, "index": index, "est_audience": est_audience}


def compute_top_dmas_for_segment(segment, dataset=None, limit=15):
    """
    Rank all DMAs for a segment dict (needs 'name' and 'targeting_params').
    Returns a list of dicts: rank, dma_code, dma_name, index, est_audience,
    population — matching ari-api's TopDma shape.
    """
    if dataset is None:
        dataset = load_dma_dataset()
    profile = parse_segment_profile(segment)
    scored = [_score_dma(d, dataset["national"], profile) for d in dataset["dmas"]]

    floor_ladder = [
        (POPULATION_FLOOR, EST_AUDIENCE_FLOOR),
        (POPULATION_FLOOR, 0),
        (RELAXED_POPULATION_FLOOR, 0),
        (0, 0),
    ]
    eligible = []
    for pop_floor, audience_floor in floor_ladder:
        eligible = [
            s
            for s in scored
            if s["dma"]["population"] >= pop_floor
            and s["est_audience"] >= audience_floor
        ]
        if len(eligible) >= limit:
            break

    # Integer-rounded index first so near-identical concentrations (generic
    # segments cluster around 100) fall through to audience size instead of
    # being ranked by demographic noise; dma code last for determinism.
    eligible.sort(
        key=lambda s: (
            -_round_half_up(s["index"]),
            -s["est_audience"],
            s["dma"]["code"],
        )
    )

    return [
        {
            "rank": i + 1,
            "dma_code": s["dma"]["code"],
            "dma_name": s["dma"]["name"],
            "index": _round_half_up(s["index"]),
            "est_audience": _round_half_up(s["est_audience"]),
            "population": s["dma"]["population"],
        }
        for i, s in enumerate(eligible[:limit])
    ]
